### ISSUE TITLE
Globbing by file paths not working

### ISSUE THREAD

**Issue by khoazero123** [duniul/clean-modules#11]
I use this command: `npx clean-modules analyze --exclude "**/googleapis/**/docs" >> clean-modules-result.json` 
But all files in `node_modules/googleapis/build/src/apis/docs` folder are still being removed.
And got this result:
```json
...
{
    "filePath": "/home/ubuntu/www/my-projects/node_modules/googleapis/build/src/apis/docs/index.js",
    "includedByDefault": true,
    "includedByGlobs": [
      {
        "original": "docs/",
        "derived": "/home/ubuntu/www/my-projects/node_modules/**/docs/**"
      }
    ]
  },
...
```

**Comment by duniul** [comment]
To include/exclude entire directories you should add `/` at the end of the glob, have you tried that? So in your case, that would be `**/googleapis/**/docs/`. 

Check out the docs for any caveats regarding the glob patterns: https://github.com/duniul/clean-modules#glob-patterns-and-configuration-file

Let me know if it works 👍
