### ISSUE TITLE
Running on node project with npm install --production returns always 0 results

### ISSUE THREAD

**Issue by wiatrM** [duniul/clean-modules#12]
Hello,

I want to shrink `node_modules` installed for nodejs procject with production flag. But none of the files are removed:

```
clean-modules

Are you sure you want to clean D:\Projects\hsk-webkd\backend\node_modules? Files will be permanently removed. (Y/N)
Y

Cleaning up node_modules...
Done in 153ms!

Cleaning up empty dirs...
Done in 0ms!

Results:
- size reduced: 0 B
- files removed: 0
- empty dirs removed: 0
```

What is the issue here?

**Comment by duniul** [comment]
Hey! Thanks for reporting this, and I'm sorry for the slow response. 🙏 

This was most likely related to an issue with paths on Windows, which has been fixed in [2.0.5](https://github.com/duniul/clean-modules/releases/tag/v2.0.5). Try it out, and reopen this issue if the problem persists!
