### ISSUE TITLE
Not finding anything to remove

### ISSUE THREAD

**Issue by tivac** [duniul/clean-modules#13]
```shell
> npx clean-modules -d -D node_modules --include "**/*.js"

clean-modules (dry run)

Cleaning up node_modules...
Done in 98ms!

Cleaning up empty dirs...
Skipped on dry runs!

Results:
- size reduced: 0 B
- files removed: 0
- empty dirs removed: 0

```

There are **definitely** `*.js` files in that folder that should've been found in this run?

### System Info

```shell
 System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 90.57 GB / 127.90 GB
  Binaries:
    Node: 16.14.2
    npm: 8.5.5
```

**Comment by duniul** [comment]
Hey! Thanks for reporting this, and I'm sorry for the slow response. 🙏 

This was most likely related to an issue with paths on Windows, which has been fixed in [2.0.5](https://github.com/duniul/clean-modules/releases/tag/v2.0.5). Try it out, and reopen this issue if the problem persists!
