### ISSUE TITLE
is there import.meta' in cjs?

### ISSUE THREAD

**Issue by ChandlerVer5** [duniul/clean-modules#21]
/Users/bing/Projects/xxxx/node_modules/clean-modules/dist/chunk-475NGVCH.cjs:113
  fileDir(import.meta),
                 ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)

vite can not get worked

**Comment by duniul** [comment]
Hey! Thanks for reporting this, I had forgotten to enable the shim injection for CJS builds and missed it since it was only present when using clean-modules programmatically. 🙈 

Try again with [v3.0.3](https://github.com/duniul/clean-modules/releases/tag/v3.0.3), which should fix the issue!
