### ISSUE TITLE
pnpm support?

### ISSUE THREAD

**Issue by eshimischi** [duniul/clean-modules#25]
Thanks for your project! Will it work with pnpm node_modules structure?

**Comment by duniul** [comment]
Yup, it works fine! 👍

At least for the `node_modules` relative to the project, and the cache folders it creates symlinks to. It won't work for the global `store` however, but that's probably a good thing!

**Comment by eshimischi** [comment]
> Yup, it works fine! 👍
> 
> At least for the `node_modules` relative to the project, and the cache folders it creates symlinks to. It won't work for the global `store` however, but that's probably a good thing!

thanks for your response!
