### ISSUE TITLE
ESLint new configuration file paths

### ISSUE THREAD

**Issue by sdavids** [duniul/clean-modules#27]
https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file

> eslint.config.js
eslint.config.mjs
eslint.config.cjs

https://github.com/duniul/clean-modules/blob/efcc25cb4b9fb754df8ec0b14b350adecbdfd5de/.cleanmodules-default#L116

**Comment by duniul** [comment]
@sdavids Thanks for reporting and adding these (including #28 #29 #30 and #31)! 🙏 They've now been merged and included in [v3.0.5](https://github.com/duniul/clean-modules/releases/tag/v3.0.5).
