### ISSUE TITLE
yargs reserved word warning

### ISSUE THREAD

**Issue by shellscape** [duniul/clean-modules#9]
Started noticing this recently, not exactly sure when it started.

```
(node:33) Warning: "version" is a reserved word.
Please do one of the following:
- Disable version with `yargs.version(false)` if using "version" as an option
- Use the built-in `yargs.version` method instead (if applicable)
- Use a different option key
https://yargs.js.org/docs/#api-reference-version
```

It seems to be related to the code here: https://github.com/duniul/clean-modules/blob/8e77f830c5b523d47906f87c8e68a988e55f5cdf/src/cli/cli.ts#L32-L37

Definitely not a critical issue, but would be nice to trim that warning from our deployment log output. Our deployment logs have alerts and filters setup around them, and the bells are going off for each deployment with the warning in there. It's an inconvenience, and not a blocker, but maybe there's something that can be done to eliminate that.

**Comment by duniul** [comment]
@shellscape Thanks for reporting this, seems like it was introduced in the latest version of Yargs 👍
